name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: macbre/push-to-ghcr@v13
      with:
        dockerfile: ./Containerfile
        image_name: ${{ github.repository }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
